### ISSUE TITLE
[Bug] Async Validator not working correctly

### ISSUE THREAD

**Issue by sven5** [Blazored/FluentValidation#38]
**Describe the bug**
When using an async validator it's still possible to submit the form with invalid data.

**To Reproduce**
I modified the Blazor Server sample code to reduce the steps to show the behavior.
1. Slightly modify the sample code for Blazor Server to only have the name field.
2. Set Task.Delay to a much higher value, i.e. 3000 to imitate a API call 
3. Enter "test" for name and submit form. 
4. Form is submitted successfully, validation occurs much later when form is already submitted with wrong data. 

**Expected behavior**
The form shouldn't be submitted with wrong data - it should wait until validation finishes and show the error.

**Screenshots**
![image](https://user-images.githubusercontent.com/8734624/93085832-79f75100-f696-11ea-9f94-0f4c27d9a4b3.png)

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor Server

**Additional context**
It seems that https://github.com/ryanelian/FluentValidation.Blazor has a possible working approach for this issue.

**Comment by punthoofd07** [comment]
I have the exact same issue

**Comment by GioviQ** [comment]
Can you post EditForm code?

**Comment by sven5** [comment]
The EditForm code is exactly the same as in [your sample](https://github.com/Blazored/FluentValidation/blob/main/samples/BlazorServer/Pages/Index.razor).

**Comment by sven5** [comment]
This is the code of EditForm:

`<EditForm Model="@Person" OnValidSubmit="@SubmitValidForm">
    <FluentValidationValidator DisableAssemblyScanning="@true" />
    <ValidationSummary />

    <p>
        <label>Name: </label>
        <InputText @bind-Value="@Person.Name" />
        <ValidationMessage For="@(() => Person.Name)" />
    </p>
    <button type="submit">Save</button>

</EditForm>`

**Comment by DouglasRiddle** [comment]
Does it still fail if you force async/await in ```OnValidSubmit```?

```C#
<EditForm Model="@Person" OnValidSubmit="@(async () => await SubmitValidForm())">
```

**Comment by DouglasRiddle** [comment]
For what it is worth, I am able to replicate this same issue with [Accelist.FluentValidation.Blazor](https://github.com/ryanelian/FluentValidation.Blazor). By default their demo project does not use ```OnValidSubmit``` so you have to code that piece in.

I did notice that FluentValidation's [Asynchronous Validation](https://docs.fluentvalidation.net/en/latest/async.html#asynchronous-validation) page has the below warning for ASP.NET validators. Could that be related to this?

> If your validator contains asynchronous validators or asynchronous conditions, it’s important that you always call ValidateAsync on your validator and never Validate. If you call Validate, then your asynchronous rules will be run synchronously, which is not desirable.
>
> You should not use asynchronous rules when [using automatic validation with ASP.NET](https://docs.fluentvalidation.net/en/latest/aspnet.html) as ASP.NET’s validation pipeline is not asynchronous. If you use asynchronous rules with ASP.NET’s automatic validation, they will always be run synchronously.

**Comment by sven5** [comment]
I tried Accelist's Validator in the past and I know it used to work. 
They left a [comment for Blazor](https://github.com/ryanelian/FluentValidation.Blazor/blob/f297bdf913032c4634493e84baa3ef0e4ef83940/FluentValidation.Blazor/FluentValidator.cs#L116).

**Comment by DouglasRiddle** [comment]
@sven5, good find. When I implement those changes in this solution, validation appears to work as expected. Do you want to test and confirm for yourself? I'm not sure what the repercussions to this change would be. @chrissainty?

I made the below changes in ```EditContextFluentValidationExtensions.cs```
Line 33
```C#
private static void ValidateModel(EditContext editContext,
```
Line 45
```C#
var validationResults = validator.Validate(context);
```

I think it is worth noting that Accelist [removed those comments with a later commit](https://github.com/ryanelian/FluentValidation.Blazor/commit/032ca73eafd9dae9aff11ea7537e413f0fd6f432#diff-1147ffe482cfb56c8a82843d767c7688L144) saying that async should now work correctly so this definitely feels like a bug.

**Comment by chrissainty** [comment]
Hey all sorry I've been off on paternity leave so now just catching up.

So this has been raised before in #31 and I [commented](https://github.com/Blazored/FluentValidation/issues/31#issuecomment-663840472) on that issue about Blazor Forms and async validation. As the forms system is event based and can't know when async validation completes it makes things quite challenging. 

Looking at the linked code from @sven5, that library has gotten around the issue by just making all validation synchronous. In my head this could lead to a locked UI if validation takes a while, however, if the user is waiting for a form submit what else would they do anyway. But this does feel like a hack rather than a real solution to the problem, as mentioned by @DouglasRiddle FluentValidation clearly states asynchronous validation only works correctly when calling `ValidateAsync`.

I'm not sure what the answer is here. Changing the library to make all validation calls synchronous could have unwanted side effects for developers and users. However, having a good solution for async validation is a must. I think I will bring this up with the Blazor team directly and get some guidance on how they see this working.

**Comment by DavidSilwal** [comment]
> @sven5, good find. When I implement those changes in this solution, validation appears to work as expected. Do you want to test and confirm for yourself? I'm not sure what the repercussions to this change would be. @chrissainty?
> 
> I made the below changes in `EditContextFluentValidationExtensions.cs`
> Line 33
> 
> ```cs
> private static void ValidateModel(EditContext editContext,
> ```
> 
> Line 45
> 
> ```cs
> var validationResults = validator.Validate(context);
> ```
> 
> I think it is worth noting that Accelist [removed those comments with a later commit](https://github.com/ryanelian/FluentValidation.Blazor/commit/032ca73eafd9dae9aff11ea7537e413f0fd6f432#diff-1147ffe482cfb56c8a82843d767c7688L144) saying that async should now work correctly so this definitely feels like a bug.

I tried your solution, I've had no luck at that Does it works in your project? Is there any temporary workaround to fix.

**Comment by DouglasRiddle** [comment]
@DavidSilwal, I modified the specified lines within ```EditContextFluentValidationExtensions.cs``` in this repo and tested based on the original post. I have not had a need for this particular feature. For my needs, the current package ([1.3.2](https://www.nuget.org/packages/Blazored.FluentValidation/1.3.2)) works in my projects.

**Comment by DavidSilwal** [comment]
@DouglasRiddle Hey, Thanks for reply. FYI I copy this code and pasted in my solution removing the package with the few modification on async await code. that worked perfectly fine without any flaw.

**Comment by Drak0sha13** [comment]
You need to create a copy to use the workaround.
In the file [EditContextFluentValidationExtensions](https://github.com/Blazored/FluentValidation/blob/main/src/Blazored.FluentValidation/EditContextFluentValidationExtensions.cs) has a method on line 39 

`private static async void ValidateModel`

the **async void** method does not wait for the call to end. 

`var validationResults = await validator.ValidateAsync(context);`
replace on
`var validationResults = validator.ValidateAsync(context).GetAwaiter().GetResult();`

similarly for method **ValidateField**

Side effect: the thread will be blocked during validation. Need to notify Blazor developers.

**Comment by Drak0sha13** [comment]
You need to create a copy to use the workaround.
In the file [EditContextFluentValidationExtensions](https://github.com/Blazored/FluentValidation/blob/main/src/Blazored.FluentValidation/EditContextFluentValidationExtensions.cs) has a method on line 39 

`private static async void ValidateModel`

the **async void** method does not wait for the call to end. 

`var validationResults = await validator.ValidateAsync(context);`
replace on
`var validationResults = Task.Run( () => validator.ValidateAsync(context)).GetAwaiter().GetResult();`

similarly for method **ValidateField**

Side effect: the thread will be blocked during validation. Need to notify Blazor developers.

**Comment by GioviQ** [comment]
I resolved in https://github.com/BlazorQ/FluentValidation/commit/3b95fb221757cb62cb68c341c17925a7fa969861

**Comment by Liero** [comment]
@GioviQ: What happens when you call `bool valid = EditContext.Validate()`? I believe it just returns the previous validation state.

**Comment by Liero** [comment]
@chrissainty:
Do you have any info whether async validation would be supported by EditContext in .NET 6?

I was thinking, that maybe the FluentValidationValidator component could expose ValidateAsync(), so that we could do at least:
```csharp
FluentValidationValidator _validator;

async Task BtnSaveClicked() {
   var validationResult = await _validator.ValidateAsync();
   if (!validationResult.IsValid) 
   {
        return;
   }
}

**Comment by GioviQ** [comment]
@Liero I use my release in prodution without issues.

**Comment by chrissainty** [comment]
@Liero There are no planned changes as far as I'm aware. Async validation is still an issue at the moment. I think we could definitely look at exposing a ValidateAsync method so it can be called manually.

**Comment by mweihberg** [comment]
We had the same problem. We wanted a client validation to check if there is always an entry of a given combination. 
Therefore we have to call a Rest service. HttpClient ist async and the call can’t be synchron because of limitations of Blazor WASM.

we architecture around it and making this kind of validation on the backend and returning ValidationProblemDetails Result in the WebApi with the FluentValidation-Errors. 
We build a custom validation component which is called „ServerSideValidation“. It is used alongside with the Blazored Component. It works like a charm. Of example code is useful i could post some snippets.

**Comment by benjaminsampica** [comment]
Yeah this is a pain in the butt. No shade intended on this library or others like it - it's a core issue for the Blazor team to solve. I'm just a little disappointed async code is so mature at this point yet async EditContext isn't a thing. Like what?

**Comment by knight1219** [comment]
> We had the same problem. We wanted a client validation to check if there is always an entry of a given combination.
> Therefore we have to call a Rest service. HttpClient ist async and the call can’t be synchron because of limitations of Blazor WASM.
> 
> we architecture around it and making this kind of validation on the backend and returning ValidationProblemDetails Result in the WebApi with the FluentValidation-Errors.
> We build a custom validation component which is called „ServerSideValidation“. It is used alongside with the Blazored Component. It works like a charm. If example code is useful i could post some snippets.

It would be great if you could share this code, ive been beating my head over this async validation stuff for 2 days now and cant seem to find a suitable solution.

**Comment by mweihberg** [comment]
Here you go...
Given an FluentValidaton RuleFor().MustAsync() in the backend.

Backend controller method to create something. We are using CQRS and MediatR. At the end the command will trigger the FluentValidation as mentioned above. If validation errors occur a FluentValidation.ValidationException is thrown.
This exception is transformed into a ValidationProblem and returned to the sender.

```
public async Task<IActionResult> CreateSomethingAsync([FromBody] CustomCreateCommand command, [FromHeader(Name = "x-requestid")] string requestId)
{
    bool commandResult = false;

    try
    {
        if (Guid.TryParse(requestId, out Guid guid) && guid != Guid.Empty)
        {
            var identifiedCommand = new IdentifiedCommand<CustomCreateCommand, bool>(command, guid);

            _logger.LogInformation(
                "----- Sending command: {CommandName} - ({@Command})",
                nameof(CustomCreateCommand),
                identifiedCommand);

            commandResult = await _mediator.Send(identifiedCommand);
        }
    }
    catch (Exception ex) when (ex.GetBaseException() is FluentValidation.ValidationException vex)
    {
        var validationResult = new ValidationResult(vex.Errors);
        validationResult.AddToModelState(ModelState, null);
        return ValidationProblem(ModelState);
    }
    catch (Exception ex)
    {
        return BadRequest(ex);
    }

    if (!commandResult)
    {
        return BadRequest();
    }

    return Ok();
}
```

Within the Blazor WASM Project we have a Service class which calls the backend via HttpClient. We also build a custom class to transport the result of the http call to the Frontend code.

Custom result class

```
public class HttpRequestResult
{
    public bool IsSuccess { get; set; }

    public HttpStatusCode StatusCode { get; set; }

    public Dictionary<string, List<string>> Errors { get; set; }

    public HttpRequestResult()
    {
        Errors = new Dictionary<string, List<string>>();
    }
}
```

Snippet from the service class. If a ValidationProblem is returned from the backend, the below code deserialize it into the custom result class from above.

```
public async Task<HttpRequestResult> AddSomeEntryAsync(Entity data, CancellationToken cancellationToken = default)
{
    try
    {
        HttpRequestResult httpRequestResult = new HttpRequestResult();

        var request = new HttpRequestMessage
        {
            RequestUri = "http://customURI"
            Method = HttpMethod.Post,
            Content = new StringContent(JsonConvert.SerializeObject(data), Encoding.UTF8, "application/json")
        };

        var responseData = await _httpClient.SendAsync(request, cancellationToken);
        var responseContent = await responseData.Content.ReadAsStringAsync();

        httpRequestResult.IsSuccess = responseData.IsSuccessStatusCode;
        httpRequestResult.StatusCode = responseData.StatusCode;

        if (!responseData.IsSuccessStatusCode)
        {
            var anonymousErrorObject = new { title = "", errors = new Dictionary<string, List<string>>() };
            var deserializedErrorObject = JsonConvert.DeserializeAnonymousType(responseContent, anonymousErrorObject);
            httpRequestResult.Errors = deserializedErrorObject.errors;
        }

        return httpRequestResult;
    }
    catch (Exception ex)
    {
        _logger.LogError(ex, ex.GetFullMessage());
        return new HttpRequestResult() { IsSuccess = false, StatusCode = System.Net.HttpStatusCode.InternalServerError };
    }
}
```

Now we need a second validator component for blazor.

```
public class ServerSideCustomValidator : ComponentBase
{
    private ValidationMessageStore messageStore;

    [CascadingParameter]
    private EditContext CurrentEditContext { get; set; }

    protected override void OnInitialized()
    {
        if (CurrentEditContext == null)
        {
            throw new InvalidOperationException(
                $"{nameof(ServerSideCustomValidator)} requires a cascading " +
                $"parameter of type {nameof(EditContext)}. " +
                $"For example, you can use {nameof(ServerSideCustomValidator)} " +
                $"inside an {nameof(EditForm)}.");
        }

        messageStore = new ValidationMessageStore(CurrentEditContext);

        CurrentEditContext.OnValidationRequested += (s, e) =>
            messageStore.Clear();
        CurrentEditContext.OnFieldChanged += (s, e) =>
            messageStore.Clear(e.FieldIdentifier);
    }

    public void DisplayErrors(Dictionary<string, List<string>> errors)
    {
        foreach (var err in errors)
        {
            messageStore.Add(CurrentEditContext.Field(err.Key), err.Value);
        }

        CurrentEditContext.NotifyValidationStateChanged();
    }

    public void ClearErrors()
    {
        messageStore.Clear();
        CurrentEditContext.NotifyValidationStateChanged();
    }
}
```

and place it into a page or component

```
<EditForm EditContext="@editContext">
    <FluentValidationValidator />
    <ServerSideCustomValidator @ref="serverSideCustomValidator" />
    ....
</EditForm>
```
Code behind to call the service class and put it all together

```
protected async Task SaveEdit()
{
    serverSideCustomValidator.ClearErrors();

    if (editContext.Validate())
    {
        HttpRequestResult result = await serviceClass.AddSomeEntryAsync(entry);

        if (!result.IsSuccess)
        {
            serverSideCustomValidator.DisplayErrors(result.Errors);
        }
        else
        {
            doSomethingForSuccess....
        }
    }

    await Task.Yield();
}
```
It is important, that the PropertyNames from the backend are similar to them in the ViewModel at the frontend. Otherwise the field cant be found in the DisplayErrors-Method of the ServerSideCustomValidator. If not so, you need a kind of mapping or display the results in a summary.

**Comment by boomalator** [comment]
While following the concepts in Chapter 5 of Blazor in action, I am getting this error:

```
[2021-03-29T21:44:03.980Z] Error: System.MissingMethodException: Method not found: 'System.Collections.Generic.IList`1<FluentValidation.Results.ValidationFailure> FluentValidation.Results.ValidationResult.get_Errors()'.
   at Blazored.FluentValidation.EditContextFluentValidationExtensions.ValidateModel(EditContext editContext, ValidationMessageStore messages, IServiceProvider serviceProvider, Boolean disableAssemblyScanning, FluentValidationValidator fluentValidationValidator, IValidator validator)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Blazored.FluentValidation.EditContextFluentValidationExtensions.ValidateModel(EditContext editContext, ValidationMessageStore messages, IServiceProvider serviceProvider, Boolean disableAssemblyScanning, FluentValidationValidator fluentValidationValidator, IValidator validator)
   at Blazored.FluentValidation.EditContextFluentValidationExtensions.<>c__DisplayClass3_0.<AddFluentValidation>b__0(Object sender, ValidationRequestedEventArgs eventArgs)
   at Microsoft.AspNetCore.Components.Forms.EditContext.Validate()
   at Microsoft.AspNetCore.Components.Forms.EditForm.HandleSubmitAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```
Frankly, I don't know where to look to find out why a method would be missing. :(

Here's the beginning of the Edit Form.

```
  <EditForm Model="@objNewPerson" OnValidSubmit="@HandleValidSubmit">
        <FluentValidationValidator />
        <FormSection Title="Personal Info">
```

Using `<DataAnnotationsValidator />` works fine (except I thought it would be easier to use fluent for the child records).

**Comment by koryphaee** [comment]
I worked around this by adding a fake message to the ValidationMessageStore before starting the async validation.
Then I await the validation task and clear the ValidationMessageStore, removing my fake message.

**Comment by chrissainty** [comment]
> I worked around this by adding a fake message to the ValidationMessageStore before starting the async validation.
Then I await the validation task and clear the ValidationMessageStore, removing my fake message.

That's an interesting idea @koryphaee.

**Comment by garaamar** [comment]
@koryphaee Could you post how you did this work around? Did you add the fake message in the validator, or somewhere else?

**Comment by koryphaee** [comment]
@garaamar It happens in the validator. I have written my own FluentValidation adapter for Blazor.
To integrate my workaround into this library you would have to insert the following code here:  https://github.com/Blazored/FluentValidation/blob/main/src/Blazored.FluentValidation/EditContextFluentValidationExtensions.cs#L48

```
var fakeIdentifier = FieldIdentifier.Create(() => editContext.Model);
messages.Add(fakeIdentifier, "Validation in progress");
editContext.NotifyValidationStateChanged();
```

**Comment by Knarzi** [comment]
If found a litte Workaround that works perfect for me with a few additional lines of code and allows me to use async Validation. First add the folowing code to the `FluentValidationValidator`:
```c#
[Parameter]
public EventCallback<bool> OnValidationExecuted { get; set; }

internal async Task NotifyValidationExecuted(bool isValid)
{
    await OnValidationExecuted.InvokeAsync( isValid);
}
```

Now add following line at the end of the ValidateModel function in the `EditContextFluentValidationExtensions` class:
```c#
await fluentValidationValidator.NotifyValidationExecuted(validationResults.IsValid);
```

Thats it. Using:

```razor
<EditForm Model="@ValidationModel" 
          OnSubmit="@HandleOnSubmit">
    <FluentValidationValidator OnValidationExecuted=@HandleValidationExecuted />
    //your form
</EditForm>
``` 
And in the code behind add the following:
```c#
private bool _isSubmit; // Indicates submit button is clicked

void HandleOnSubmit()
{
    _isSubmit = true;  // Submit is active
    FluentValidator.Validate((o) => o.IncludeAllRuleSets());  //  Execute validation without checking the result
}

//Executed when the async validation is done
private void HandleValidationExecuted(bool isValid)
{
    if (!isValid || !_isSubmit) // must be valid and in submit state, else reset submit state and retun
    {
        _isSubmit = false;
        return;
    }
    
    //Your final submit code
}
```
Not a perfect solution, but for me a perfect and simple workaround.

**Comment by chrissainty** [comment]
@koryphaee Could you provide a more complete code example of even better open a PR with your suggestions. I'm very interested in this approach and it could be the answer we've all been looking for.

**Comment by koryphaee** [comment]
I have created a pull request: https://github.com/Blazored/FluentValidation/pull/73

It works fairly well with one big problem.
When the submit button is pressed the EditForm validates the entire model via the OnValidationRequested event.
Immediately after that it calls GetValidationMessages() leaving no time for the async validation to complete.

There are two solutions:
- Running the model validation synchronously
- Not using the built-in submit functionality at all

In the PR I have opted for the first solution because it's easier to implement.
Please don't merge it as it's terrible.

The second solution would require some sort of custom button component that performs async validation.
Since the EditForm allows no access to it's registered validator the implementation would be a bit more complex.

I do not plan on putting a lot more time into this because I have spent so many hours trying to get the EditForm and EditContext to work that I can't stand using them any more.

**Comment by felinepc** [comment]
Whew. I'm a new developer who just spent hours finding out that a lone `MustAsync` call in one of my rules was the reason why one of my forms kept triggering `OnValidSubmit` despite the validation clearly failing.

Reading through the comments here, my understanding is that there's no "perfect" solution to this problem yet because `EditForm` does not natively support async validation.

So I changed the `MustAsync` call to `Must` using the synchronous workaround `Task.Run( () => MyMethod).GetAwaiter().GetResult()`.

Being a new developer, I just want to make sure that the worst thing this does, is to briefly lock the UI/thread of the individual user filling out/submitting that particular form. It's unlikely going to cause any subsequent issues or burn down my entire web server, right?

Some assurance from the other seasoned developers would be greatly appreciated!

**Comment by Thundarr1974** [comment]
I use a custom model validation library based on Data Annotations that leverages async validations and I recently came up against this same issue in WASM.  My workaround was to sub-class the EditForm component and leverage the EditContext "Properties" to hook-up async support.  Below are basics - hope it helps someone else..

EditForm
`    public class EditFormEx : EditForm
    {
        public EditFormEx()
        {
            typeof(EditForm)
                .GetField("_handleSubmitDelegate", BindingFlags.Instance | BindingFlags.NonPublic)
                .SetValue(this, (Func<Task>)HandleSubmitAsyncEx);
        }

        async Task HandleSubmitAsyncEx()
        {
            if (OnSubmit.HasDelegate)
            {
                // When using OnSubmit, the developer takes control of the validation lifecycle
                await OnSubmit.InvokeAsync(EditContext);
            }
            else
            {
                // Otherwise, the system implicitly runs validation on form submission

                var isValid = await EditContext.ValidateAsync();

                if (isValid && OnValidSubmit.HasDelegate)
                {
                    await OnValidSubmit.InvokeAsync(EditContext);
                }

                if (!isValid && OnInvalidSubmit.HasDelegate)
                {
                    await OnInvalidSubmit.InvokeAsync(EditContext);
                }
            }
        }
    }
`
Custom "ModelValidator" Component
`        protected override void OnInitialized()
        {
            if (CurrentEditContext == null)
            {
                throw new InvalidOperationException($"{nameof(ModelValidator)} requires a cascading " +
                    $"parameter of type {nameof(EditContext)}. For example, you can use {nameof(ModelValidator)} " +
                    $"inside an EditForm.");
            }

            // No simple way to perform async validation with EditContext in WASM
            // https://github.com/Blazored/FluentValidation/issues/38

            Messages = new ValidationMessageStore(CurrentEditContext);

            CurrentEditContext.OnFieldChanged += (sender, args) => OnFieldChanged(CurrentEditContext, args.FieldIdentifier);
            CurrentEditContext.Properties[nameof(EditContext.OnValidationRequested) + "Async"] = (Func<EditContext, Task<bool>>)OnValidationRequested;
            
            StoredEditContext = CurrentEditContext;
        }
...
        async Task<bool> OnValidationRequested(EditContext editContext)
        {
            var (isValid, errors) = await Validator.Validate(editContext.Model);
...
            editContext.NotifyValidationStateChanged();
            return isValid;
        }
`
Extension method for EditContext
`    public static class EditContextExtensions
    {
        public static async Task<bool> ValidateAsync(this EditContext editContext)
        {
            if (editContext.Properties.TryGetValue(nameof(EditContext.OnValidationRequested) + "Async", out var v) && v is Func<EditContext, Task<bool>> fx)
            {                
                return await fx.Invoke(editContext);
            }
            else
            {
                return editContext.Validate();
            }
        }
    }
`

**Comment by IvanJosipovic** [comment]
Has anyone found a working solution/workaround for this?

**Comment by michac** [comment]
In my fork I updated the FluentValidationEditContextExtensions to stash an operationId in the EditContext properties each time it starts a validation operation, and take it out when it finishes. Then I added a new extension method called WaitForAsyncValidation that will sleep and spin until Properties has no operations in progress. This could be used in your own OnSubmit handler to be called after a EditContext.Validate to pause for completion before checking validation messages. I also added an optional Submit button component that does the "validate -> wait for async" steps for you and just calls your handler OnValidSubmit. (it also disables the submit button while validating and submitting).

I did not submit a pull request for this because the Properties property of EditContext requires .NET 5.0. I also don't know what the contention implications are for the EditContext.Properties object in the Blazor Server environment (vs single threaded WebAssembly). 

https://github.com/michac/FluentValidation/commit/19d251929245543859ddd9f96916c2e47996504e

Unfortunately my opinion is that the real solution is to add async validation to the EditForm and every workaround is going to feel pretty hacky.

**Comment by hex2bit** [comment]
For those looking for an easy way to add an async custom validation step to their form submission using EditForm, this is about the simplest version I've come up with until proper async support is added.

You'll need to use the EditContext and ValidationMessageStore in order to add custom error messages.  This is a bit clunky and I wish it had a simple one-liner to add a custom validation error messages to any field or the form in general _(hint hint)_.

In your code, add an OnValidationRequested event handler to do your custom validation work.  That will get called before the form's validation is run.  After the form validation succeeds, it will call the OnValidSubmit handler.  Because of the lack of async support, you'll need to use a couple flags to track when both your validation and the form validation succeeds.  Then call a third method to do the submission work only once both flags are set to true.
```
// need these to add custom validation messages
private ValidationMessageStore messageStore;
private EditContext editContext;

// my form model
private MyModel myModel = new MyModel();
// my flags to track validation success
private bool asyncValidationResult;
private bool formValidationResult;

protected override void OnInitialized()
{
	editContext = new EditContext(myModel);
	messageStore = new ValidationMessageStore(editContext);

	// add my custom validation handler
	editContext.OnValidationRequested += MyCustomValidationHandler;
}

// this is called before OnValidSubmit
private async void MyCustomValidationHandler(object sender, ValidationRequestedEventArgs args)
{
	// clear errors and our validation result flags
	messageStore.Clear();
	asyncValidationResult = false;
	formValidationResult = false;

	// form submit will not wait for this async call to finish
	if (await checkForDuplicate(myModel.Name))
	{
		// add validation error and notify so form updates
		messageStore.Add(editContext.Field("Name"), "This name is already taken");
		editContext.NotifyFieldChanged(editContext.Field("Name"));
	}
	else
	{
		// all good, set validation result to true and call our submit handler
		asyncValidationResult = true;
		await HandleSubmitAsync();
	}
}

public async void OnValidSubmit(EditContext editContext)
{
	// this is call before above validation completes but after data annotation validation
	// has succeeded, so just save flag to say this succeeded and call our submit handleer
	formValidationResult = true;
	await HandleSubmitAsync();
}

private async Task HandleSubmitAsync()
{
	// check to see if both validation succeeded and submit was called
	if (asyncValidationResult && formValidationResult)
	{
		// do whatever work you want to do on valid form submission
		await myServier.CreateUser(myModel);
	}
}

public void Dispose()
{
	editContext.OnValidationRequested -= MyCustomValidationHandler;
}
```

Typical form tied to the EditContext.  Really wish you could just tie it to the model and still add custom validation messages.
```
<EditForm EditContext="editContext" OnValidSubmit="@OnValidSubmit">
	<label for="Name">Name:</label>
	<InputText id="Name" @bind-Value="myModel.Name" placeholder="Enter a name" />
	<ValidationMessage For=@(() => myModel.Name) />
	
	<button type="submit">Submit</button>
</EditForm>
```

**Comment by Liero** [comment]
I have a simpler workaround ready to be used now.

You can override `ValidateAsync` method of your Validator and store the result (`Task<ValidationResult>`) somewhere. In OnSubmit handler you can await the task in order to wait until the `ValidateAsync` completes.

```razor
<FluentValidationValidator Validator="modelValidator" />

@code {
    AccountValidator validator = new AccountValidator();

    async Task OnSubmit(EditContext editContext)
    {
        editContext.Validate();
        await validator.WaitForValidateAsync();

        if (editContext.GetValidationMessages().Any())
        {
             //invalid
            return;
        }
       //valid
    }
}
```

```csharp
   public class AccountValidator : AsyncAbstractValidator <Account>
   {
       public AccountValidator() 
       {
            RuleFor(e => e.Username).MustAsync(...).WithMessage("This user name is already taken!");
       }
   }

    public abstract class AsyncAbstractValidator<T> : AbstractValidator<T>
    {
        Task<ValidationResult> validateTask;


        public override Task<ValidationResult> ValidateAsync(ValidationContext<T> context, CancellationToken cancellation = default)
            => validateTask = base.ValidateAsync(context, cancellation);        

        public override ValidationResult Validate(ValidationContext<T> context)
        {
            var result = base.Validate(context);
            validateTask = Task.FromResult(result);
            return result;
        }

        public Task<ValidationResult> WaitForValidateAsync()
             => validateTask ?? Task.FromResult<ValidationResult>(null);
        
    }
```


The limitation is, that OnValidSubmit callback will not automatically wait for async validation, but you can still wait explicitly using await validator.WaitForValidateAsync();

**Comment by nielsNocore** [comment]
i was struggling for a good solution, the changes in #137 did not work for me, where i wanted to validate i could not create a ref to the fluentValdation compontent. 

But did had a reference to the EditContext. using the flowing extension method. 
Inspired by `FluentValidationValidator.ValidateAsync()` i was able to create a working ValidateAsync Extension method for the EditContext. 

```
public static class EditContextExtensions
 {
    public static async Task<bool> ValidateAsync(this EditContext editContext)
    {
        editContext.Validate();
        await GetValidationResultAsync(editContext);
        return !editContext.GetValidationMessages().Any();
    }

    public static Task<ValidationResult> GetValidationResultAsync(this EditContext editContext)
    {
        return editContext.Properties.TryGetValue(EditContextFluentValidationExtensions.PendingAsyncValidation, out object? validateAsyncTask)
            ? (Task<ValidationResult>)validateAsyncTask
            : throw new InvalidOperationException("ValidationResult not found.");
    }
}
```

now i was able to just call `await EditContext.ValidateAsync()`

Mabey this can help others getting Ascync validations to work. 
Niels
